services:
  frontend:
    build: 
      context: ./frontend
      args:
        DATABASE_URL: ${DATABASE_URL}
    container_name: knowledge-navigator-frontend
    networks:
      - kn-net
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    environment:
      - BACKEND_URL="http://host.docker.internal:8000"
      - NEXT_PUBLIC_BACKEND_URL="http://localhost:8000"
      - DATABASE_URL="postgresql://myuser:secret@db:5432/postgres?schema=public"
    extra_hosts:
    - "host.docker.internal:host-gateway"
  db:
    image: postgres
    restart: always
    networks:
      - kn-net
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  pgdata:

networks:
  kn-net: