services:
  frontend:
    build: 
      context: ./frontend
      args:
        DATABASE_URL: ${DATABASE_URL}
    network_mode: host
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    extra_hosts:
    - "host.docker.internal:host-gateway"
  backend:
    build: 
      context: ./backend
      args:
        DATABASE_URL: ${DATABASE_URL}
    network_mode: host
  db:
    image: postgres
    restart: always
    network_mode: host
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  pgdata:

networks:
  kn-net: